env:
  global:
    secure: doX67gTa1G43+jOOyezjNK7A8h+GR/hm+h5/JgRwyupxssxtJJs80G4O9ojTNZgByMd2hvdV2ZQSJMlIeTdJpp5z1wqOovOxswIFGcEXvfKKK/+WOeK4QAvhik0QKaLZGA9aRkT95k0zWRLBHTdqe56VgfwNYBVUUE9PpauCEuA=
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - doxygen
    - graphviz
script:
- ./autogen.sh
- ./configure
- make dist
- tar xvzf yahttp-git.tar.gz
- cd yahttp-git
- ./configure
- make
- make check
sudo: false
