env:
  global:
    - secure: "jLryW1QxSlUIaRDcKgSwKTWrH+Is2SH0+ZDLjwxxCiWqNuuFAEUIgPDEQJLErdwBTYV+dkU5O1k+/Eal8XzgEny2ACMIfOpLgKe9pAgCJOJMLSbN/m+E9jMY7I0w1vKOnevdGK7ZB8WL6v4DmvQbUyvBwSxCRXjZJdWJKlBKv/M=" 
language: cpp
compiler:
  - gcc
  - clang
addons:
 apt:
  packages:
   - libboost-test-dev
   - doxygen
   - graphviz
script:
 - ./autogen.sh
 - ./configure
 - make dist
 - tar xvzf yahttp-git.tar.gz
 - cd yahttp-git
 - ./configure
 - make
 - make check
sudo: false
#addons:
#  coverity_scan:
#    project:
#      name: "cmouse/yahttp"
#      description: "Yet Another HTTP Library"
#    notification_email: cmouse@desteem.org
#    build_command_prepend: "./autogen.sh && ./configure"
#    build_command: make
#    branch_pattern: master
