env:
  global:
    secure: doX67gTa1G43+jOOyezjNK7A8h+GR/hm+h5/JgRwyupxssxtJJs80G4O9ojTNZgByMd2hvdV2ZQSJMlIeTdJpp5z1wqOovOxswIFGcEXvfKKK/+WOeK4QAvhik0QKaLZGA9aRkT95k0zWRLBHTdqe56VgfwNYBVUUE9PpauCEuA=
language: cpp
compiler:
- gcc
- clang
script:
- ./autogen.sh
- ./configure
- make dist
- tar xvzf yahttp-git.tar.gz
- cd yahttp-git
- ./configure
- make
- make check
sudo: false
addons:
  apt:
    packages:
    - libboost-test-dev
    - doxygen
    - graphviz
  coverity_scan:
    project:
      name: "cmouse/yahttp"
      description: "Yet Another HTTP Library"
    notification_email: cmouse@desteem.org
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: make
    branch_pattern: master
